
name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: run app tests
        run: |
            echo "running tests..."
            pwd
            npm install
            npm run test


    
  